local luacov_runner = require "luacov.runner"
local deftest = require("deftest.deftest")

function init(self)
	print('[DefTest]: Init of DefTest')

	luacov_runner.init()
	deftest.add(require("test.tests.test_button"))
	deftest.add(require("test.tests.test_hover"))
	deftest.add(require("test.tests.test_drag"))
	deftest.add(require("test.tests.test_back_handler"))
	deftest.add(require("test.tests.test_blocker"))

	local is_report = (sys.get_config("test.report") == "1")
	deftest.run({ coverage = { enabled = is_report } })
end
