return {
    data = {
        animations = {
            {
                animation_id = "default",
                animation_keys = {
                },
                duration = 1,
            },
            {
                animation_id = "hold",
                animation_keys = {
                    {
                        easing = "outsine",
                        end_value = -90,
                        key_type = "tween",
                        node_id = "button_image",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "outsine",
                        end_value = 90,
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.15,
                        easing = "outsine",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "button",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.15,
                        easing = "outsine",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "button",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.15,
                        easing = "outsine",
                        end_value = 1.3,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.15,
                        easing = "outsine",
                        end_value = 1.3,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 1,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "fill_angle",
                        start_value = 360,
                    },
                    {
                        duration = 0.85,
                        easing = "incirc",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "button",
                        property_id = "scale_x",
                        start_time = 0.15,
                        start_value = 1.1,
                    },
                    {
                        duration = 0.85,
                        easing = "incirc",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "button",
                        property_id = "scale_y",
                        start_time = 0.15,
                        start_value = 1.1,
                    },
                    {
                        duration = 0.51,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_x",
                        start_time = 0.49,
                        start_value = 1.3,
                    },
                    {
                        duration = 0.51,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_y",
                        start_time = 0.49,
                        start_value = 1.3,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "complete",
                animation_keys = {
                    {
                        data = "false",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text",
                        property_id = "inherit_alpha",
                        start_data = "true",
                    },
                    {
                        easing = "outsine",
                        end_value = 0.62,
                        key_type = "tween",
                        node_id = "button_image",
                        property_id = "color_b",
                        start_value = 0.62,
                    },
                    {
                        easing = "outsine",
                        end_value = 0.88,
                        key_type = "tween",
                        node_id = "button_image",
                        property_id = "color_g",
                        start_value = 0.835,
                    },
                    {
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "button_image",
                        property_id = "color_r",
                        start_value = 0.557,
                    },
                    {
                        duration = 0.17,
                        easing = "outsine",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "root",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.17,
                        easing = "outsine",
                        end_value = 1.2,
                        key_type = "tween",
                        node_id = "root",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.17,
                        easing = "outsine",
                        end_value = 1.2,
                        key_type = "tween",
                        node_id = "root",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.38,
                        easing = "outsine",
                        end_value = 0.56,
                        key_type = "tween",
                        node_id = "button_image",
                        property_id = "color_r",
                        start_time = 0.02,
                        start_value = 0.9,
                    },
                    {
                        duration = 0.38,
                        easing = "outsine",
                        end_value = 0.62,
                        key_type = "tween",
                        node_id = "button_image",
                        property_id = "color_b",
                        start_time = 0.02,
                        start_value = 0.62,
                    },
                    {
                        duration = 0.38,
                        easing = "outsine",
                        end_value = 0.84,
                        key_type = "tween",
                        node_id = "button_image",
                        property_id = "color_g",
                        start_time = 0.02,
                        start_value = 0.88,
                    },
                    {
                        duration = 0.22,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "root",
                        property_id = "color_a",
                        start_time = 0.17,
                        start_value = 1.1,
                    },
                    {
                        duration = 0.22,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "root",
                        property_id = "scale_x",
                        start_time = 0.17,
                        start_value = 1.2,
                    },
                    {
                        duration = 0.22,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "root",
                        property_id = "scale_y",
                        start_time = 0.17,
                        start_value = 1.2,
                    },
                    {
                        data = "true",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text",
                        property_id = "inherit_alpha",
                        start_data = "false",
                        start_time = 0.39,
                    },
                },
                duration = 0.4,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "/example/examples/basic/button/basic_button_hold.gui",
            layers = {
            },
            settings = {
                font_size = 40,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}