local druid = require "druid.druid"

function init(self)
	self.druid = druid.new(self)

	self.button = self.druid:new_button("button", function()
		print("New click")
	end)
end

function update(self, dt)
	self.druid:update(dt)
end

function on_message(self, message_id, message, sender)
	self.druid:on_message(message_id, message, sender)
end

function on_input(self, action_id, action)
	self.druid:on_input(action_id, action)
end