local druid = require("druid.druid")
local lang = require("example.lang")


local function setup_druid()
	druid.set_sound_function(function(name)
		sound.play("example:/sound#" .. name)
	end)

	druid.set_text_function(function(lang_id, ...)
		return lang.get_locale(lang_id, ...)
	end)

	druid.on_language_change()
end


function init(self)
	setup_druid()
	msg.post("@render:", "clear_color", { color = vmath.vector4(0.8, 0.9, 0.85, 1) })
end
