return {
    version = 1,
    format = "json",
    data = {
        animations = {
            {
                duration = 12,
                animation_id = "idle",
                animation_keys = {
                    {
                        node_id = "icon_druid_left",
                        duration = 3,
                        end_value = -5,
                        easing = "outsine",
                        key_type = "tween",
                        property_id = "position_y",
                    },
                    {
                        node_id = "icon_druid_right",
                        duration = 3,
                        end_value = -5,
                        easing = "outsine",
                        key_type = "tween",
                        property_id = "position_y",
                    },
                    {
                        node_id = "icon_logo",
                        duration = 4,
                        end_value = 5,
                        easing = "outsine",
                        key_type = "tween",
                        property_id = "position_y",
                    },
                    {
                        start_time = 3,
                        duration = 3,
                        start_value = -5,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "icon_druid_left",
                        end_value = 5,
                        property_id = "position_y",
                    },
                    {
                        start_time = 3,
                        duration = 3,
                        start_value = -5,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "icon_druid_right",
                        end_value = 5,
                        property_id = "position_y",
                    },
                    {
                        start_time = 4,
                        duration = 8,
                        start_value = 5,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "icon_logo",
                        property_id = "position_y",
                    },
                    {
                        start_time = 6,
                        duration = 6,
                        start_value = 5,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "icon_druid_left",
                        property_id = "position_y",
                    },
                    {
                        start_time = 6,
                        duration = 6,
                        start_value = 5,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "icon_druid_right",
                        property_id = "position_y",
                    },
                },
            },
            {
                duration = 0.6,
                animation_id = "on_hover_in",
                animation_keys = {
                    {
                        node_id = "W_Anchor",
                        duration = 0.6,
                        end_value = -220,
                        easing = "outsine",
                        key_type = "tween",
                        start_value = -200,
                        property_id = "position_x",
                    },
                    {
                        node_id = "text_description",
                        duration = 0.6,
                        end_value = -60,
                        easing = "outsine",
                        key_type = "tween",
                        start_value = -50,
                        property_id = "position_y",
                    },
                    {
                        node_id = "icon_druid_left",
                        duration = 0.6,
                        end_value = 0.7,
                        easing = "outsine",
                        key_type = "tween",
                        start_value = 0.5,
                        property_id = "color_a",
                    },
                    {
                        node_id = "icon_druid_right",
                        duration = 0.6,
                        end_value = 0.7,
                        easing = "outsine",
                        key_type = "tween",
                        start_value = 0.5,
                        property_id = "color_a",
                    },
                    {
                        node_id = "icon_logo",
                        duration = 0.6,
                        end_value = 1.1,
                        easing = "outsine",
                        key_type = "tween",
                        start_value = 1,
                        property_id = "scale_x",
                    },
                    {
                        node_id = "icon_logo",
                        duration = 0.6,
                        end_value = 1.1,
                        easing = "outsine",
                        key_type = "tween",
                        start_value = 1,
                        property_id = "scale_y",
                    },
                    {
                        node_id = "icon_logo",
                        duration = 0.6,
                        end_value = 1.7,
                        easing = "outsine",
                        key_type = "tween",
                        start_value = 1,
                        property_id = "color_a",
                    },
                    {
                        node_id = "E_Anchor",
                        duration = 0.6,
                        end_value = 220,
                        easing = "outsine",
                        key_type = "tween",
                        start_value = 200,
                        property_id = "position_x",
                    },
                },
            },
            {
                duration = 0.3,
                animation_id = "on_hover_out",
                animation_keys = {
                    {
                        node_id = "W_Anchor",
                        duration = 0.3,
                        end_value = -200,
                        easing = "outback",
                        key_type = "tween",
                        start_value = -200,
                        property_id = "position_x",
                    },
                    {
                        node_id = "text_description",
                        duration = 0.3,
                        end_value = -50,
                        easing = "outback",
                        key_type = "tween",
                        start_value = -50,
                        property_id = "position_y",
                    },
                    {
                        node_id = "icon_druid_left",
                        duration = 0.3,
                        end_value = 0.5,
                        easing = "outsine",
                        key_type = "tween",
                        start_value = 0.5,
                        property_id = "color_a",
                    },
                    {
                        node_id = "icon_druid_right",
                        duration = 0.3,
                        end_value = 0.5,
                        easing = "outsine",
                        key_type = "tween",
                        start_value = 0.5,
                        property_id = "color_a",
                    },
                    {
                        node_id = "icon_logo",
                        duration = 0.3,
                        end_value = 1,
                        easing = "outsine",
                        key_type = "tween",
                        start_value = 1,
                        property_id = "color_a",
                    },
                    {
                        node_id = "icon_logo",
                        duration = 0.3,
                        end_value = 1,
                        easing = "outback",
                        key_type = "tween",
                        start_value = 1,
                        property_id = "scale_x",
                    },
                    {
                        node_id = "icon_logo",
                        duration = 0.3,
                        end_value = 1,
                        easing = "outback",
                        key_type = "tween",
                        start_value = 1,
                        property_id = "scale_y",
                    },
                    {
                        node_id = "E_Anchor",
                        duration = 0.3,
                        end_value = 200,
                        easing = "outback",
                        key_type = "tween",
                        start_value = 200,
                        property_id = "position_x",
                    },
                },
            },
        },
        metadata = {
            gui_path = "/example/components/druid_logo/druid_logo.gui",
            settings = {
                font_size = 40,
            },
            gizmo_steps = {
                time = 0.1,
            },
            layers = {
                {
                    name = "druid",
                    color = "73E84C",
                },
                {
                    name = "druid_logo",
                    color = "90D2F6",
                },
                {
                    name = "text_regular",
                    color = "C379F0",
                },
            },
            fps = 60,
        },
        nodes = {
        },
    },
    type = "animation_editor",
}