return {
    version = 1,
    format = "json",
    data = {
        animations = {
            {
                duration = 0.35,
                animation_keys = {
                    {
                        key_type = "trigger",
                        data = "C",
                        property_id = "text",
                        start_data = "Hover Me!",
                        easing = "linear",
                        node_id = "button/text",
                    },
                    {
                        key_type = "tween",
                        node_id = "button/root",
                        easing = "outsine",
                        end_value = 0.624,
                        property_id = "color_b",
                        start_value = 0.961,
                        duration = 0.35,
                    },
                    {
                        key_type = "tween",
                        node_id = "button/root",
                        easing = "outsine",
                        end_value = 0.875,
                        property_id = "color_g",
                        start_value = 0.843,
                        duration = 0.35,
                    },
                    {
                        key_type = "tween",
                        node_id = "button/root",
                        easing = "outsine",
                        end_value = 0.902,
                        property_id = "color_r",
                        start_value = 0.631,
                        duration = 0.35,
                    },
                    {
                        key_type = "tween",
                        node_id = "button/root",
                        easing = "outback",
                        end_value = 1.3,
                        property_id = "scale_x",
                        start_value = 1,
                        duration = 0.35,
                    },
                    {
                        key_type = "tween",
                        node_id = "button/root",
                        easing = "outback",
                        end_value = 1.3,
                        property_id = "scale_y",
                        start_value = 1,
                        duration = 0.35,
                    },
                    {
                        key_type = "trigger",
                        start_time = 0.047,
                        data = "Cl",
                        start_data = "C",
                        property_id = "text",
                        easing = "linear",
                        node_id = "button/text",
                    },
                    {
                        key_type = "trigger",
                        start_time = 0.1,
                        data = "Cli",
                        start_data = "Cl",
                        property_id = "text",
                        easing = "linear",
                        node_id = "button/text",
                    },
                    {
                        key_type = "trigger",
                        start_time = 0.145,
                        data = "Clic",
                        start_data = "Cli",
                        property_id = "text",
                        easing = "linear",
                        node_id = "button/text",
                    },
                    {
                        key_type = "trigger",
                        start_time = 0.195,
                        data = "Click",
                        start_data = "Clic",
                        property_id = "text",
                        easing = "linear",
                        node_id = "button/text",
                    },
                    {
                        key_type = "trigger",
                        start_time = 0.24,
                        data = "Click M",
                        start_data = "Click",
                        property_id = "text",
                        easing = "linear",
                        node_id = "button/text",
                    },
                    {
                        key_type = "trigger",
                        start_time = 0.293,
                        data = "Click Me",
                        start_data = "Click M",
                        property_id = "text",
                        easing = "linear",
                        node_id = "button/text",
                    },
                    {
                        key_type = "trigger",
                        start_time = 0.34,
                        data = "Click Me!",
                        start_data = "Click Me",
                        property_id = "text",
                        easing = "linear",
                        node_id = "button/text",
                    },
                },
                animation_id = "on_hover",
            },
            {
                duration = 0.35,
                initial_state = "on_hover",
                animation_id = "on_click",
                animation_keys = {
                    {
                        key_type = "trigger",
                        data = "BOOM",
                        property_id = "text",
                        start_data = "Click Me!",
                        easing = "linear",
                        node_id = "button/text",
                    },
                    {
                        key_type = "tween",
                        node_id = "button/text",
                        easing = "outsine",
                        end_value = 1.3,
                        property_id = "scale_x",
                        start_value = 1,
                        duration = 0.1,
                    },
                    {
                        key_type = "tween",
                        node_id = "button/text",
                        easing = "outsine",
                        end_value = 1.3,
                        property_id = "scale_y",
                        start_value = 1,
                        duration = 0.1,
                    },
                    {
                        key_type = "tween",
                        node_id = "button/root",
                        easing = "outsine",
                        end_value = 0.608,
                        property_id = "color_b",
                        start_value = 0.624,
                        duration = 0.2,
                    },
                    {
                        key_type = "tween",
                        node_id = "button/root",
                        easing = "outsine",
                        end_value = 0.608,
                        property_id = "color_g",
                        start_value = 0.875,
                        duration = 0.2,
                    },
                    {
                        key_type = "tween",
                        node_id = "button/root",
                        easing = "outsine",
                        end_value = 0.957,
                        property_id = "color_r",
                        start_value = 0.902,
                        duration = 0.2,
                    },
                    {
                        key_type = "tween",
                        node_id = "button/root",
                        easing = "outback",
                        end_value = 1.6,
                        property_id = "scale_x",
                        start_value = 1.3,
                        duration = 0.2,
                    },
                    {
                        key_type = "tween",
                        node_id = "button/root",
                        easing = "outback",
                        end_value = 1.6,
                        property_id = "scale_y",
                        start_value = 1.3,
                        duration = 0.2,
                    },
                    {
                        node_id = "button/text",
                        key_type = "tween",
                        start_time = 0.1,
                        easing = "outsine",
                        end_value = 1,
                        property_id = "scale_x",
                        start_value = 1.3,
                        duration = 0.13,
                    },
                    {
                        node_id = "button/text",
                        key_type = "tween",
                        start_time = 0.1,
                        easing = "outsine",
                        end_value = 1,
                        property_id = "scale_y",
                        start_value = 1.3,
                        duration = 0.13,
                    },
                },
            },
            {
                duration = 0.5,
                animation_keys = {
                    {
                        key_type = "trigger",
                        data = "Hover Me!",
                        property_id = "text",
                        start_data = "BOOM",
                        easing = "linear",
                        node_id = "button/text",
                    },
                    {
                        key_type = "tween",
                        node_id = "button/text",
                        easing = "outsine",
                        end_value = 1,
                        property_id = "scale_x",
                        start_value = 1,
                        duration = 0.2,
                    },
                    {
                        key_type = "tween",
                        node_id = "button/text",
                        easing = "outsine",
                        end_value = 1,
                        property_id = "scale_y",
                        start_value = 1,
                        duration = 0.2,
                    },
                    {
                        key_type = "tween",
                        node_id = "button/root",
                        easing = "outsine",
                        end_value = 0.627,
                        property_id = "color_r",
                        start_value = 0.957,
                        duration = 0.5,
                    },
                    {
                        key_type = "tween",
                        node_id = "button/root",
                        easing = "outsine",
                        end_value = 0.839,
                        property_id = "color_g",
                        start_value = 0.608,
                        duration = 0.5,
                    },
                    {
                        key_type = "tween",
                        node_id = "button/root",
                        easing = "outsine",
                        end_value = 0.961,
                        property_id = "color_b",
                        start_value = 0.608,
                        duration = 0.5,
                    },
                    {
                        key_type = "tween",
                        node_id = "button/root",
                        easing = "outsine",
                        end_value = 1,
                        property_id = "scale_x",
                        start_value = 1.5,
                        duration = 0.5,
                    },
                    {
                        key_type = "tween",
                        node_id = "button/root",
                        easing = "outsine",
                        end_value = 1,
                        property_id = "scale_y",
                        start_value = 1.5,
                        duration = 0.5,
                    },
                },
                animation_id = "reset",
            },
        },
        metadata = {
            gui_path = "/example/examples/panthera/basic_animation/basic_animation.gui",
            layers = {
            },
            fps = 60,
            gizmo_steps = {
            },
            settings = {
                font_size = 40,
            },
        },
        nodes = {
        },
    },
    type = "animation_editor",
}