return {
    data = {
        animations = {
            {
                animation_id = "default",
                duration = 1,
                animation_keys = {
                },
            },
            {
                animation_id = "horizontal",
                duration = 1,
                animation_keys = {
                    {
                        key_type = "tween",
                        node_id = "eyes",
                        easing = "outsine",
                        end_value = -20,
                        property_id = "position_x",
                    },
                    {
                        key_type = "tween",
                        node_id = "mouth",
                        easing = "outsine",
                        end_value = -20,
                        property_id = "position_x",
                    },
                    {
                        key_type = "tween",
                        node_id = "mouth",
                        easing = "outsine",
                        end_value = -4,
                        property_id = "rotation_z",
                    },
                    {
                        key_type = "tween",
                        node_id = "hand_right",
                        start_value = -1,
                        end_value = -0.8,
                        easing = "outsine",
                        property_id = "scale_x",
                    },
                    {
                        key_type = "tween",
                        node_id = "eye_left",
                        start_value = 1,
                        end_value = 0.8,
                        easing = "outsine",
                        property_id = "scale_x",
                    },
                    {
                        key_type = "tween",
                        node_id = "eye_left",
                        start_value = 1,
                        end_value = 0.8,
                        easing = "outsine",
                        property_id = "scale_y",
                    },
                    {
                        key_type = "tween",
                        node_id = "hand_right",
                        start_value = 1,
                        end_value = 0.8,
                        easing = "outsine",
                        property_id = "scale_y",
                    },
                    {
                        key_type = "tween",
                        node_id = "mouth",
                        start_value = 1,
                        end_value = 0.9,
                        easing = "outsine",
                        property_id = "scale_x",
                    },
                    {
                        key_type = "tween",
                        node_id = "mouth",
                        start_value = 1,
                        end_value = 0.9,
                        easing = "outsine",
                        property_id = "scale_y",
                    },
                    {
                        key_type = "tween",
                        node_id = "hand_left",
                        start_value = 1,
                        end_value = 1.2,
                        easing = "outsine",
                        property_id = "color_a",
                    },
                    {
                        key_type = "tween",
                        node_id = "hand_left",
                        start_value = 1,
                        end_value = 1.5,
                        easing = "outsine",
                        property_id = "scale_x",
                    },
                    {
                        key_type = "tween",
                        node_id = "hand_left",
                        start_value = 1,
                        end_value = 1.5,
                        easing = "outsine",
                        property_id = "scale_y",
                    },
                    {
                        key_type = "tween",
                        node_id = "eye_left",
                        easing = "outsine",
                        end_value = 2,
                        property_id = "position_y",
                    },
                    {
                        key_type = "tween",
                        node_id = "hand_left",
                        start_value = 130,
                        end_value = 110,
                        easing = "outsine",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.75,
                        key_type = "tween",
                        node_id = "eye_left",
                        easing = "outsine",
                        start_value = 2,
                        property_id = "position_y",
                    },
                    {
                        duration = 0.75,
                        key_type = "tween",
                        node_id = "eye_left",
                        easing = "outsine",
                        end_value = 1,
                        start_value = 0.8,
                        property_id = "scale_x",
                    },
                    {
                        duration = 0.75,
                        key_type = "tween",
                        node_id = "eye_left",
                        easing = "outsine",
                        end_value = 1,
                        start_value = 0.8,
                        property_id = "scale_y",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "hand_right",
                        easing = "linear",
                        end_value = -110,
                        start_value = -130,
                        property_id = "position_x",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "hand_right",
                        easing = "outsine",
                        end_value = -1.5,
                        start_value = -0.8,
                        property_id = "scale_x",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "hand_left",
                        easing = "outsine",
                        end_value = 0.8,
                        start_value = 1.5,
                        property_id = "scale_x",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "hand_left",
                        easing = "outsine",
                        end_value = 0.8,
                        start_value = 1.5,
                        property_id = "scale_y",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "hand_left",
                        easing = "outsine",
                        end_value = 1,
                        start_value = 1.2,
                        property_id = "color_a",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "mouth",
                        easing = "inoutsine",
                        end_value = 1.1,
                        start_value = 0.9,
                        property_id = "scale_x",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "mouth",
                        easing = "inoutsine",
                        end_value = 1.1,
                        start_value = 0.9,
                        property_id = "scale_y",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "hand_right",
                        easing = "outsine",
                        end_value = 1.2,
                        start_value = 1,
                        property_id = "color_a",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "hand_right",
                        easing = "outsine",
                        end_value = 1.5,
                        start_value = 0.8,
                        property_id = "scale_y",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "mouth",
                        easing = "inoutsine",
                        end_value = 4,
                        start_value = -4,
                        property_id = "rotation_z",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "eyes",
                        easing = "inoutsine",
                        end_value = 20,
                        start_value = -20,
                        property_id = "position_x",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "mouth",
                        easing = "inoutsine",
                        end_value = 20,
                        start_value = -20,
                        property_id = "position_x",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "hand_left",
                        easing = "linear",
                        end_value = 130,
                        start_value = 110,
                        property_id = "position_x",
                    },
                    {
                        duration = 0.75,
                        key_type = "tween",
                        node_id = "eye_right",
                        easing = "outsine",
                        start_value = 1,
                        end_value = 0.8,
                        start_time = 0.25,
                        property_id = "scale_x",
                    },
                    {
                        duration = 0.75,
                        key_type = "tween",
                        node_id = "eye_right",
                        easing = "outsine",
                        start_value = 1,
                        end_value = 0.8,
                        start_time = 0.25,
                        property_id = "scale_y",
                    },
                    {
                        duration = 0.75,
                        key_type = "tween",
                        node_id = "eye_right",
                        easing = "outsine",
                        end_value = 2,
                        start_time = 0.25,
                        property_id = "position_y",
                    },
                },
            },
            {
                animation_id = "vertical",
                duration = 1,
                animation_keys = {
                    {
                        key_type = "tween",
                        node_id = "mouth",
                        start_value = -35,
                        end_value = -50,
                        easing = "outsine",
                        property_id = "position_y",
                    },
                    {
                        key_type = "tween",
                        node_id = "hand_left",
                        easing = "outsine",
                        end_value = -35,
                        property_id = "position_y",
                    },
                    {
                        key_type = "tween",
                        node_id = "hand_left",
                        start_value = -10,
                        end_value = -35,
                        easing = "outsine",
                        property_id = "rotation_z",
                    },
                    {
                        key_type = "tween",
                        node_id = "hand_right",
                        easing = "outsine",
                        end_value = -35,
                        property_id = "position_y",
                    },
                    {
                        key_type = "tween",
                        node_id = "eyes",
                        start_value = 2,
                        end_value = -10,
                        easing = "outsine",
                        property_id = "position_y",
                    },
                    {
                        key_type = "tween",
                        node_id = "brow_left",
                        start_value = 5,
                        easing = "outsine",
                        property_id = "rotation_z",
                    },
                    {
                        key_type = "tween",
                        node_id = "brow_right",
                        start_value = -5,
                        easing = "outsine",
                        property_id = "rotation_z",
                    },
                    {
                        key_type = "trigger",
                        node_id = "hand_left",
                        easing = "linear",
                        data = "animation_blend/pink_hand_point",
                        start_data = "animation_blend/pink_hand_open",
                        property_id = "texture",
                    },
                    {
                        key_type = "trigger",
                        node_id = "hand_right",
                        easing = "linear",
                        data = "animation_blend/pink_hand_point",
                        start_data = "animation_blend/pink_hand_open",
                        property_id = "texture",
                    },
                    {
                        key_type = "trigger",
                        node_id = "mouth",
                        easing = "linear",
                        data = "animation_blend/facial_part_mouth_smirk",
                        start_data = "animation_blend/facial_part_mouth_happy",
                        property_id = "texture",
                    },
                    {
                        key_type = "tween",
                        node_id = "hand_right",
                        start_value = 10,
                        end_value = 35,
                        easing = "outsine",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "mouth",
                        easing = "inoutsine",
                        end_value = -20,
                        start_value = -50,
                        property_id = "position_y",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "brow_right",
                        easing = "outsine",
                        end_value = -10,
                        property_id = "rotation_z",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "brow_left",
                        easing = "outsine",
                        end_value = -5,
                        property_id = "position_x",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "hand_left",
                        easing = "outsine",
                        start_value = -35,
                        property_id = "rotation_z",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "hand_right",
                        easing = "outsine",
                        start_value = 35,
                        property_id = "rotation_z",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "character",
                        easing = "outsine",
                        end_value = 0.96,
                        start_value = 1,
                        property_id = "scale_x",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "character",
                        easing = "outsine",
                        end_value = 1.04,
                        start_value = 1,
                        property_id = "scale_y",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "brow_right",
                        easing = "outsine",
                        end_value = 5,
                        property_id = "position_x",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "brow_left",
                        easing = "outsine",
                        end_value = 15,
                        property_id = "rotation_z",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "eyes",
                        easing = "inoutsine",
                        end_value = 25,
                        start_value = -10,
                        property_id = "position_y",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "hand_left",
                        easing = "insine",
                        end_value = 100,
                        start_value = -35,
                        property_id = "position_y",
                    },
                    {
                        duration = 1,
                        key_type = "tween",
                        node_id = "hand_right",
                        easing = "insine",
                        end_value = 100,
                        start_value = -35,
                        property_id = "position_y",
                    },
                    {
                        start_time = 0.4,
                        key_type = "trigger",
                        node_id = "hand_left",
                        easing = "linear",
                        data = "animation_blend/pink_hand_closed",
                        start_data = "animation_blend/pink_hand_point",
                        property_id = "texture",
                    },
                    {
                        start_time = 0.4,
                        key_type = "trigger",
                        node_id = "hand_right",
                        easing = "linear",
                        data = "animation_blend/pink_hand_closed",
                        start_data = "animation_blend/pink_hand_point",
                        property_id = "texture",
                    },
                    {
                        start_time = 0.41,
                        key_type = "trigger",
                        node_id = "mouth",
                        easing = "linear",
                        data = "animation_blend/facial_part_mouth_happy",
                        start_data = "animation_blend/facial_part_mouth_smirk",
                        property_id = "texture",
                    },
                    {
                        start_time = 0.62,
                        key_type = "trigger",
                        node_id = "eye_left",
                        easing = "linear",
                        data = "animation_blend/facial_part_eye_half_top",
                        start_data = "animation_blend/facial_part_eye_open",
                        property_id = "texture",
                    },
                    {
                        start_time = 0.62,
                        key_type = "trigger",
                        node_id = "eye_right",
                        easing = "linear",
                        data = "animation_blend/facial_part_eye_half_top",
                        start_data = "animation_blend/facial_part_eye_open",
                        property_id = "texture",
                    },
                    {
                        start_time = 0.78,
                        key_type = "trigger",
                        node_id = "hand_left",
                        easing = "linear",
                        data = "animation_blend/pink_hand_open",
                        start_data = "animation_blend/pink_hand_closed",
                        property_id = "texture",
                    },
                    {
                        start_time = 0.78,
                        key_type = "trigger",
                        node_id = "hand_right",
                        easing = "linear",
                        data = "animation_blend/pink_hand_open",
                        start_data = "animation_blend/pink_hand_closed",
                        property_id = "texture",
                    },
                },
            },
            {
                animation_id = "idle",
                duration = 3,
                animation_keys = {
                    {
                        duration = 0.75,
                        key_type = "tween",
                        node_id = "body",
                        easing = "outsine",
                        end_value = 0.98,
                        start_value = 1,
                        property_id = "scale_y",
                    },
                    {
                        duration = 0.75,
                        key_type = "tween",
                        node_id = "body",
                        easing = "outsine",
                        end_value = 1.02,
                        start_value = 1,
                        property_id = "scale_x",
                    },
                    {
                        duration = 1.37,
                        key_type = "tween",
                        node_id = "body",
                        easing = "outsine",
                        start_value = 1.02,
                        end_value = 0.98,
                        start_time = 0.75,
                        property_id = "scale_x",
                    },
                    {
                        duration = 1.37,
                        key_type = "tween",
                        node_id = "body",
                        easing = "outsine",
                        start_value = 0.98,
                        end_value = 1.02,
                        start_time = 0.75,
                        property_id = "scale_y",
                    },
                    {
                        duration = 0.88,
                        key_type = "tween",
                        node_id = "body",
                        easing = "outsine",
                        start_value = 0.98,
                        end_value = 1,
                        start_time = 2.12,
                        property_id = "scale_x",
                    },
                    {
                        duration = 0.88,
                        key_type = "tween",
                        node_id = "body",
                        easing = "outsine",
                        start_value = 1.02,
                        end_value = 1,
                        start_time = 2.12,
                        property_id = "scale_y",
                    },
                },
            },
        },
        metadata = {
            gui_path = "/example/examples/panthera/animation_blend/animation_blend.gui",
            gizmo_steps = {
            },
            layers = {
            },
            fps = 60,
            settings = {
                font_size = 40,
            },
        },
        nodes = {
        },
    },
    version = 1,
    type = "animation_editor",
    format = "json",
}