return {
    data = {
        animations = {
            {
                animation_id = "default",
                animation_keys = {
                },
                duration = 1,
            },
            {
                animation_id = "idle",
                animation_keys = {
                    {
                        duration = 2,
                        easing = "outsine",
                        end_value = 370,
                        key_type = "tween",
                        node_id = "icon_druid_left",
                        property_id = "position_y",
                        start_value = 375,
                    },
                    {
                        duration = 2,
                        easing = "outsine",
                        end_value = 370,
                        key_type = "tween",
                        node_id = "icon_druid_right",
                        property_id = "position_y",
                        start_value = 375,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.38,
                        key_type = "tween",
                        node_id = "icon_heart1",
                        property_id = "color_g",
                        start_time = 0.7,
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.737,
                        key_type = "tween",
                        node_id = "icon_heart1",
                        property_id = "color_b",
                        start_time = 0.7,
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.941,
                        key_type = "tween",
                        node_id = "icon_heart1",
                        property_id = "color_r",
                        start_time = 0.7,
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart1",
                        property_id = "color_a",
                        start_time = 0.7,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "icon_heart1",
                        property_id = "scale_x",
                        start_time = 0.7,
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "icon_heart1",
                        property_id = "scale_y",
                        start_time = 0.7,
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 1.2,
                        key_type = "tween",
                        node_id = "sponsor_github",
                        property_id = "color_a",
                        start_time = 0.7,
                        start_value = 0.75,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "icon_heart1",
                        property_id = "color_a",
                        start_time = 1.4,
                        start_value = 1,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart1",
                        property_id = "color_b",
                        start_time = 1.4,
                        start_value = 0.737,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart1",
                        property_id = "color_g",
                        start_time = 1.4,
                        start_value = 0.38,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart1",
                        property_id = "color_r",
                        start_time = 1.4,
                        start_value = 0.941,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart1",
                        property_id = "scale_x",
                        start_time = 1.4,
                        start_value = 1.1,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart1",
                        property_id = "scale_y",
                        start_time = 1.4,
                        start_value = 1.1,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "sponsor_github",
                        property_id = "color_a",
                        start_time = 1.4,
                        start_value = 1.2,
                    },
                    {
                        duration = 2.5,
                        easing = "outsine",
                        end_value = 380,
                        key_type = "tween",
                        node_id = "icon_druid_left",
                        property_id = "position_y",
                        start_time = 2,
                        start_value = 370,
                    },
                    {
                        duration = 2.5,
                        easing = "outsine",
                        end_value = 380,
                        key_type = "tween",
                        node_id = "icon_druid_right",
                        property_id = "position_y",
                        start_time = 2,
                        start_value = 370,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.353,
                        key_type = "tween",
                        node_id = "icon_heart2",
                        property_id = "color_b",
                        start_time = 3.7,
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart2",
                        property_id = "color_a",
                        start_time = 3.7,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart2",
                        property_id = "color_g",
                        start_time = 3.7,
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart2",
                        property_id = "color_r",
                        start_time = 3.7,
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "icon_heart2",
                        property_id = "scale_x",
                        start_time = 3.7,
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "icon_heart2",
                        property_id = "scale_y",
                        start_time = 3.7,
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 1.2,
                        key_type = "tween",
                        node_id = "sponsor_coffee",
                        property_id = "color_a",
                        start_time = 3.7,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 1.2,
                        key_type = "tween",
                        node_id = "icon_druid_left",
                        property_id = "color_a",
                        start_time = 4.15,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 1.2,
                        key_type = "tween",
                        node_id = "icon_druid_right",
                        property_id = "color_a",
                        start_time = 4.15,
                        start_value = 0.75,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "icon_heart2",
                        property_id = "color_a",
                        start_time = 4.4,
                        start_value = 1,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart2",
                        property_id = "color_b",
                        start_time = 4.4,
                        start_value = 0.353,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart2",
                        property_id = "color_g",
                        start_time = 4.4,
                        start_value = 1,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart2",
                        property_id = "color_r",
                        start_time = 4.4,
                        start_value = 1,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart2",
                        property_id = "scale_x",
                        start_time = 4.4,
                        start_value = 1.1,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart2",
                        property_id = "scale_y",
                        start_time = 4.4,
                        start_value = 1.1,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "sponsor_coffee",
                        property_id = "color_a",
                        start_time = 4.4,
                        start_value = 1.2,
                    },
                    {
                        duration = 1.15,
                        easing = "outsine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "icon_druid_left",
                        property_id = "color_a",
                        start_time = 4.5,
                        start_value = 1.2,
                    },
                    {
                        duration = 1.15,
                        easing = "outsine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "icon_druid_right",
                        property_id = "color_a",
                        start_time = 4.5,
                        start_value = 1.2,
                    },
                    {
                        duration = 5.5,
                        easing = "insine",
                        end_value = 375,
                        key_type = "tween",
                        node_id = "icon_druid_left",
                        property_id = "position_y",
                        start_time = 4.5,
                        start_value = 380,
                    },
                    {
                        duration = 5.5,
                        easing = "insine",
                        end_value = 375,
                        key_type = "tween",
                        node_id = "icon_druid_right",
                        property_id = "position_y",
                        start_time = 4.5,
                        start_value = 380,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.478,
                        key_type = "tween",
                        node_id = "icon_heart3",
                        property_id = "color_b",
                        start_time = 6.7,
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.494,
                        key_type = "tween",
                        node_id = "icon_heart3",
                        property_id = "color_g",
                        start_time = 6.7,
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart3",
                        property_id = "color_a",
                        start_time = 6.7,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart3",
                        property_id = "color_r",
                        start_time = 6.7,
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "icon_heart3",
                        property_id = "scale_x",
                        start_time = 6.7,
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "icon_heart3",
                        property_id = "scale_y",
                        start_time = 6.7,
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 1.2,
                        key_type = "tween",
                        node_id = "sponsor_kofi",
                        property_id = "color_a",
                        start_time = 6.7,
                        start_value = 0.75,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "icon_heart3",
                        property_id = "color_a",
                        start_time = 7.4,
                        start_value = 1,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart3",
                        property_id = "color_b",
                        start_time = 7.4,
                        start_value = 0.478,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart3",
                        property_id = "color_g",
                        start_time = 7.4,
                        start_value = 0.494,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart3",
                        property_id = "color_r",
                        start_time = 7.4,
                        start_value = 1,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart3",
                        property_id = "scale_x",
                        start_time = 7.4,
                        start_value = 1.1,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_heart3",
                        property_id = "scale_y",
                        start_time = 7.4,
                        start_value = 1.1,
                    },
                    {
                        duration = 1,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "sponsor_kofi",
                        property_id = "color_a",
                        start_time = 7.4,
                        start_value = 1.2,
                    },
                },
                duration = 10,
            },
            {
                animation_id = "click_left",
                animation_keys = {
                    {
                        duration = 0.08,
                        easing = "outsine",
                        end_value = -2,
                        key_type = "tween",
                        node_id = "text_hello",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.08,
                        easing = "outquad",
                        end_value = 0.72,
                        key_type = "tween",
                        node_id = "icon_druid_left",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.08,
                        easing = "outsine",
                        end_value = 1.2,
                        key_type = "tween",
                        node_id = "icon_druid_left",
                        property_id = "color_a",
                        start_value = 0.75,
                    },
                    {
                        duration = 0.08,
                        easing = "outquad",
                        end_value = 1.22,
                        key_type = "tween",
                        node_id = "icon_druid_left",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.08,
                        easing = "outsine",
                        end_value = 5,
                        key_type = "tween",
                        node_id = "text_hello",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.08,
                        easing = "outsine",
                        end_value = 235,
                        key_type = "tween",
                        node_id = "text_hello",
                        property_id = "position_y",
                        start_value = 240,
                    },
                    {
                        duration = 0.09,
                        easing = "outsine",
                        end_value = -2,
                        key_type = "tween",
                        node_id = "icon_druid_right",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.09,
                        easing = "outsine",
                        end_value = 185,
                        key_type = "tween",
                        node_id = "icon_druid_right",
                        property_id = "position_x",
                        start_value = 180,
                    },
                    {
                        duration = 0.42,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_druid_left",
                        property_id = "scale_x",
                        start_time = 0.08,
                        start_value = 1.22,
                    },
                    {
                        duration = 0.42,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_druid_left",
                        property_id = "scale_y",
                        start_time = 0.08,
                        start_value = 0.72,
                    },
                    {
                        duration = 0.47,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "text_hello",
                        property_id = "position_x",
                        start_time = 0.08,
                        start_value = 5,
                    },
                    {
                        duration = 0.47,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "text_hello",
                        property_id = "rotation_z",
                        start_time = 0.08,
                        start_value = -2,
                    },
                    {
                        duration = 0.47,
                        easing = "outsine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "icon_druid_left",
                        property_id = "color_a",
                        start_time = 0.08,
                        start_value = 1.2,
                    },
                    {
                        duration = 0.47,
                        easing = "outsine",
                        end_value = 240,
                        key_type = "tween",
                        node_id = "text_hello",
                        property_id = "position_y",
                        start_time = 0.08,
                        start_value = 235,
                    },
                    {
                        duration = 0.46,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "icon_druid_right",
                        property_id = "rotation_z",
                        start_time = 0.09,
                        start_value = -2,
                    },
                    {
                        duration = 0.46,
                        easing = "outsine",
                        end_value = 180,
                        key_type = "tween",
                        node_id = "icon_druid_right",
                        property_id = "position_x",
                        start_time = 0.09,
                        start_value = 185,
                    },
                },
                duration = 0.55,
            },
            {
                animation_id = "click_right",
                animation_keys = {
                    {
                        duration = 0.08,
                        easing = "outsine",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "text_hello",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.08,
                        easing = "outquad",
                        end_value = 0.72,
                        key_type = "tween",
                        node_id = "icon_druid_right",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.08,
                        easing = "outsine",
                        end_value = 1.2,
                        key_type = "tween",
                        node_id = "icon_druid_right",
                        property_id = "color_a",
                        start_value = 0.75,
                    },
                    {
                        duration = 0.08,
                        easing = "outquad",
                        end_value = 1.22,
                        key_type = "tween",
                        node_id = "icon_druid_right",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.08,
                        easing = "outsine",
                        end_value = -5,
                        key_type = "tween",
                        node_id = "text_hello",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.08,
                        easing = "outsine",
                        end_value = 235,
                        key_type = "tween",
                        node_id = "text_hello",
                        property_id = "position_y",
                        start_value = 240,
                    },
                    {
                        duration = 0.09,
                        easing = "outsine",
                        end_value = -185,
                        key_type = "tween",
                        node_id = "icon_druid_left",
                        property_id = "position_x",
                        start_value = -180,
                    },
                    {
                        duration = 0.09,
                        easing = "outsine",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "icon_druid_left",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.42,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_druid_right",
                        property_id = "scale_x",
                        start_time = 0.08,
                        start_value = 1.22,
                    },
                    {
                        duration = 0.42,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon_druid_right",
                        property_id = "scale_y",
                        start_time = 0.08,
                        start_value = 0.72,
                    },
                    {
                        duration = 0.47,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "text_hello",
                        property_id = "position_x",
                        start_time = 0.08,
                        start_value = -5,
                    },
                    {
                        duration = 0.47,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "text_hello",
                        property_id = "rotation_z",
                        start_time = 0.08,
                        start_value = 2,
                    },
                    {
                        duration = 0.47,
                        easing = "outsine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "icon_druid_right",
                        property_id = "color_a",
                        start_time = 0.08,
                        start_value = 1.2,
                    },
                    {
                        duration = 0.47,
                        easing = "outsine",
                        end_value = 240,
                        key_type = "tween",
                        node_id = "text_hello",
                        property_id = "position_y",
                        start_time = 0.08,
                        start_value = 235,
                    },
                    {
                        duration = 0.46,
                        easing = "outsine",
                        end_value = -180,
                        key_type = "tween",
                        node_id = "icon_druid_left",
                        property_id = "position_x",
                        start_time = 0.09,
                        start_value = -185,
                    },
                    {
                        duration = 0.46,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "icon_druid_left",
                        property_id = "rotation_z",
                        start_time = 0.09,
                        start_value = 2,
                    },
                },
                duration = 0.55,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "example/examples/intro/intro/intro.gui",
            layers = {
                {
                    color = "73E84C",
                    name = "druid_logo",
                },
                {
                    color = "90D2F6",
                    name = "text_regular",
                },
            },
            settings = {
                font_size = 40,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}