return {
    version = 1,
    format = "json",
    type = "animation_editor",
    data = {
        metadata = {
            fps = 60,
            layers = {
                {
                    name = "druid_logo",
                    color = "73E84C",
                },
                {
                    name = "text_regular",
                    color = "90D2F6",
                },
            },
            gui_path = "/example/examples/intro/intro/intro.gui",
            settings = {
                font_size = 40,
            },
            gizmo_steps = {
            },
        },
        nodes = {
        },
        animations = {
            {
                animation_id = "default",
                duration = 1,
                animation_keys = {
                },
            },
            {
                animation_id = "idle",
                duration = 10,
                animation_keys = {
                    {
                        node_id = "icon_druid_left",
                        property_id = "position_y",
                        duration = 2,
                        easing = "outsine",
                        start_value = 375,
                        key_type = "tween",
                        end_value = 370,
                    },
                    {
                        node_id = "icon_druid_right",
                        property_id = "position_y",
                        duration = 2,
                        easing = "outsine",
                        start_value = 375,
                        key_type = "tween",
                        end_value = 370,
                    },
                    {
                        end_value = 0.737,
                        node_id = "icon_heart1",
                        property_id = "color_b",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 0.7,
                    },
                    {
                        end_value = 0.38,
                        node_id = "icon_heart1",
                        property_id = "color_g",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 0.7,
                    },
                    {
                        end_value = 0.941,
                        node_id = "icon_heart1",
                        property_id = "color_r",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 0.7,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart1",
                        property_id = "color_a",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 0.75,
                        key_type = "tween",
                        start_time = 0.7,
                    },
                    {
                        end_value = 1.1,
                        node_id = "icon_heart1",
                        property_id = "scale_x",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 0.7,
                    },
                    {
                        end_value = 1.1,
                        node_id = "icon_heart1",
                        property_id = "scale_y",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 0.7,
                    },
                    {
                        end_value = 1.2,
                        node_id = "sponsor_github",
                        property_id = "color_a",
                        start_value = 0.75,
                        easing = "outsine",
                        duration = 0.7,
                        key_type = "tween",
                        start_time = 0.7,
                    },
                    {
                        end_value = 0.75,
                        node_id = "icon_heart1",
                        property_id = "color_a",
                        duration = 1,
                        easing = "insine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 1.4,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart1",
                        property_id = "color_b",
                        duration = 1,
                        easing = "insine",
                        start_value = 0.737,
                        key_type = "tween",
                        start_time = 1.4,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart1",
                        property_id = "color_g",
                        duration = 1,
                        easing = "insine",
                        start_value = 0.38,
                        key_type = "tween",
                        start_time = 1.4,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart1",
                        property_id = "color_r",
                        duration = 1,
                        easing = "insine",
                        start_value = 0.941,
                        key_type = "tween",
                        start_time = 1.4,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart1",
                        property_id = "scale_x",
                        duration = 1,
                        easing = "insine",
                        start_value = 1.1,
                        key_type = "tween",
                        start_time = 1.4,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart1",
                        property_id = "scale_y",
                        duration = 1,
                        easing = "insine",
                        start_value = 1.1,
                        key_type = "tween",
                        start_time = 1.4,
                    },
                    {
                        end_value = 1,
                        node_id = "sponsor_github",
                        property_id = "color_a",
                        start_value = 1.2,
                        easing = "insine",
                        duration = 1,
                        key_type = "tween",
                        start_time = 1.4,
                    },
                    {
                        end_value = 380,
                        node_id = "icon_druid_left",
                        property_id = "position_y",
                        duration = 2.5,
                        easing = "outsine",
                        start_value = 370,
                        key_type = "tween",
                        start_time = 2,
                    },
                    {
                        end_value = 380,
                        node_id = "icon_druid_right",
                        property_id = "position_y",
                        duration = 2.5,
                        easing = "outsine",
                        start_value = 370,
                        key_type = "tween",
                        start_time = 2,
                    },
                    {
                        end_value = 0.353,
                        node_id = "icon_heart2",
                        property_id = "color_b",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 3.7,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart2",
                        property_id = "color_g",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 3.7,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart2",
                        property_id = "color_r",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 3.7,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart2",
                        property_id = "color_a",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 0.75,
                        key_type = "tween",
                        start_time = 3.7,
                    },
                    {
                        end_value = 1.1,
                        node_id = "icon_heart2",
                        property_id = "scale_x",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 3.7,
                    },
                    {
                        end_value = 1.1,
                        node_id = "icon_heart2",
                        property_id = "scale_y",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 3.7,
                    },
                    {
                        end_value = 1.2,
                        node_id = "sponsor_coffee",
                        property_id = "color_a",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 0.75,
                        key_type = "tween",
                        start_time = 3.7,
                    },
                    {
                        end_value = 1.2,
                        node_id = "icon_druid_left",
                        property_id = "color_a",
                        duration = 0.35,
                        easing = "outsine",
                        start_value = 0.75,
                        key_type = "tween",
                        start_time = 4.15,
                    },
                    {
                        end_value = 1.2,
                        node_id = "icon_druid_right",
                        property_id = "color_a",
                        duration = 0.35,
                        easing = "outsine",
                        start_value = 0.75,
                        key_type = "tween",
                        start_time = 4.15,
                    },
                    {
                        end_value = 0.75,
                        node_id = "icon_heart2",
                        property_id = "color_a",
                        duration = 1,
                        easing = "insine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 4.4,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart2",
                        property_id = "color_b",
                        duration = 1,
                        easing = "insine",
                        start_value = 0.353,
                        key_type = "tween",
                        start_time = 4.4,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart2",
                        property_id = "color_g",
                        duration = 1,
                        easing = "insine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 4.4,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart2",
                        property_id = "color_r",
                        duration = 1,
                        easing = "insine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 4.4,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart2",
                        property_id = "scale_x",
                        duration = 1,
                        easing = "insine",
                        start_value = 1.1,
                        key_type = "tween",
                        start_time = 4.4,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart2",
                        property_id = "scale_y",
                        duration = 1,
                        easing = "insine",
                        start_value = 1.1,
                        key_type = "tween",
                        start_time = 4.4,
                    },
                    {
                        end_value = 1,
                        node_id = "sponsor_coffee",
                        property_id = "color_a",
                        duration = 1,
                        easing = "insine",
                        start_value = 1.2,
                        key_type = "tween",
                        start_time = 4.4,
                    },
                    {
                        end_value = 0.75,
                        node_id = "icon_druid_left",
                        property_id = "color_a",
                        duration = 1.15,
                        easing = "outsine",
                        start_value = 1.2,
                        key_type = "tween",
                        start_time = 4.5,
                    },
                    {
                        end_value = 0.75,
                        node_id = "icon_druid_right",
                        property_id = "color_a",
                        duration = 1.15,
                        easing = "outsine",
                        start_value = 1.2,
                        key_type = "tween",
                        start_time = 4.5,
                    },
                    {
                        end_value = 375,
                        node_id = "icon_druid_left",
                        property_id = "position_y",
                        duration = 5.5,
                        easing = "insine",
                        start_value = 380,
                        key_type = "tween",
                        start_time = 4.5,
                    },
                    {
                        end_value = 375,
                        node_id = "icon_druid_right",
                        property_id = "position_y",
                        duration = 5.5,
                        easing = "insine",
                        start_value = 380,
                        key_type = "tween",
                        start_time = 4.5,
                    },
                    {
                        end_value = 0.478,
                        node_id = "icon_heart3",
                        property_id = "color_b",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 6.7,
                    },
                    {
                        end_value = 0.494,
                        node_id = "icon_heart3",
                        property_id = "color_g",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 6.7,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart3",
                        property_id = "color_r",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 6.7,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart3",
                        property_id = "color_a",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 0.75,
                        key_type = "tween",
                        start_time = 6.7,
                    },
                    {
                        end_value = 1.1,
                        node_id = "icon_heart3",
                        property_id = "scale_x",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 6.7,
                    },
                    {
                        end_value = 1.1,
                        node_id = "icon_heart3",
                        property_id = "scale_y",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 6.7,
                    },
                    {
                        end_value = 1.2,
                        node_id = "sponsor_kofi",
                        property_id = "color_a",
                        duration = 0.7,
                        easing = "outsine",
                        start_value = 0.75,
                        key_type = "tween",
                        start_time = 6.7,
                    },
                    {
                        end_value = 0.75,
                        node_id = "icon_heart3",
                        property_id = "color_a",
                        duration = 1,
                        easing = "insine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 7.4,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart3",
                        property_id = "color_b",
                        duration = 1,
                        easing = "insine",
                        start_value = 0.478,
                        key_type = "tween",
                        start_time = 7.4,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart3",
                        property_id = "color_g",
                        duration = 1,
                        easing = "insine",
                        start_value = 0.494,
                        key_type = "tween",
                        start_time = 7.4,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart3",
                        property_id = "color_r",
                        duration = 1,
                        easing = "insine",
                        start_value = 1,
                        key_type = "tween",
                        start_time = 7.4,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart3",
                        property_id = "scale_x",
                        duration = 1,
                        easing = "insine",
                        start_value = 1.1,
                        key_type = "tween",
                        start_time = 7.4,
                    },
                    {
                        end_value = 1,
                        node_id = "icon_heart3",
                        property_id = "scale_y",
                        duration = 1,
                        easing = "insine",
                        start_value = 1.1,
                        key_type = "tween",
                        start_time = 7.4,
                    },
                    {
                        end_value = 1,
                        node_id = "sponsor_kofi",
                        property_id = "color_a",
                        duration = 1,
                        easing = "insine",
                        start_value = 1.2,
                        key_type = "tween",
                        start_time = 7.4,
                    },
                },
            },
        },
    },
}