return {
    data = {
        animations = {
            {
                animation_id = "default",
                animation_keys = {
                    {
                        easing = "outsine",
                        end_value = 1.6,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        end_value = 1.6,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.15,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_x",
                        start_value = 1.6,
                    },
                    {
                        duration = 0.15,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_y",
                        start_value = 1.6,
                    },
                    {
                        duration = 0.39,
                        easing = "outsine",
                        end_value = 400,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "position_y",
                        start_value = 190,
                    },
                    {
                        duration = 0.43,
                        easing = "outsine",
                        end_value = 300,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "size_y",
                        start_value = 120,
                    },
                    {
                        duration = 1,
                        easing = "inoutexpo",
                        end_value = 720,
                        key_type = "tween",
                        node_id = "root",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.24,
                        easing = "outsine",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_x",
                        start_time = 0.15,
                        start_value = 1,
                    },
                    {
                        duration = 0.24,
                        easing = "outsine",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_y",
                        start_time = 0.15,
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "color_b",
                        start_time = 0.31,
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "color_g",
                        start_time = 0.31,
                        start_value = 1,
                    },
                    {
                        duration = 0.61,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_x",
                        start_time = 0.39,
                        start_value = 2,
                    },
                    {
                        duration = 0.61,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_y",
                        start_time = 0.39,
                        start_value = 2,
                    },
                    {
                        duration = 0.26,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "color_b",
                        start_time = 0.61,
                    },
                    {
                        duration = 0.26,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "color_g",
                        start_time = 0.61,
                    },
                    {
                        duration = 0.36,
                        easing = "outsine",
                        end_value = 190,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "position_y",
                        start_time = 0.62,
                        start_value = 400,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 120,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "size_y",
                        start_time = 0.65,
                        start_value = 300,
                    },
                },
                duration = 1,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "/example/other/go_bindings/go_widget.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}